=== CataMark/java-navision-etl-app/src/main/resources/queries.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://catalin.anyinternational.com"
           xmlns="http://catalin.anyinternational.com"
           elementFormDefault="qualified">
    
    <!-- definition of simple elements -->
    <xs:element name="sourceQuery" type="xs:string">
        <xs:annotation>
            <xs:appinfo>MS NAV 2017 ELT to Postgresql</xs:appinfo>
            <xs:documentation xml:lang="en">The T-SQL query in Microsoft Dynamics Navision 2017 for obtaining the source records.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="sourceQueryParam" type="xs:string"/>
    <xs:element name="targetTable" type="xs:string"/>
    <xs:element name="targetCallfront" type="xs:string"/>
    <xs:element name="targetCallback" type="xs:string"/>
    
    <!-- definition of complex elements -->
    <xs:element name="step">
        <xs:complexType>
            <xs:all>
                <xs:element ref="targetCallfront"/>
                <xs:element ref="sourceQuery"/>
                <xs:element ref="sourceQueryParam"/>
                <xs:element ref="targetTable"/>
                <xs:element ref="targetCallback"/>
            </xs:all>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="order" type="xs:positiveInteger" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- definition of parent element -->
    <xs:element name="queries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="step" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CataMark/java-navision-etl-app/src/main/resources/queries.xml
<?xml version="1.0" encoding="UTF-8"?>
<queries xmlns="http://catalin.anyinternational.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://catalin.anyinternational.com queries.xsd">
    <step name="Production BOM Header" order="1">
        <targetCallfront>truncate table nav.tbl_int_prod_bom_header_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[No_],
                a.[Description],
                a.[Description 2],
                a.[Search Name],
                a.[Unit of Measure Code],
                a.[Low-Level Code],
                a.[Creation Date],
                a.[Last Date Modified],
                a.[Status],
                a.[Version Nos_],
                a.[No_ Series],
                a.[Type],
                current_timestamp as mod_de
            from [dbo].[Live_any$Production BOM Header] as a
            where cast(a.[timestamp] as bigint) > ?;
        </sourceQuery>
        <sourceQueryParam>
            select rowvers from nav.fnc_last_rowvers_get('nav.tbl_int_prod_bom_header');
        </sourceQueryParam>
        <targetTable>nav.tbl_int_prod_bom_header_load</targetTable>
        <!-- NO CALLBACK HERE -->
        <targetCallback />
    </step>
    <step name="Production BOM Line" order="2">
        <targetCallfront>truncate table nav.tbl_int_prod_bom_line_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[Production BOM No_],
                a.[Version Code],
                a.[Line No_],
                a.[Type],
                a.[No_],
                a.[Description],
                a.[Unit of Measure Code],
                a.[Quantity],
                a.[Position],
                a.[Position 2],
                a.[Position 3],
                a.[Lead-Time Offset],
                a.[Routing Link Code],
                a.[Scrap _],
                a.[Variant Code],
                a.[Starting Date],
                a.[Ending Date],
                a.[Length],
                a.[Width],
                a.[Weight],
                a.[Depth],
                a.[Calculation Formula],
                a.[Quantity per],
                a.[Fitting Note],
                a.[Parcel Code],
                a.[Randament _],
                a.[Rebut _],
                current_timestamp as mod_de
            from [dbo].[Live_any$Production BOM Line] as a
            inner join [dbo].[Live_any$Production BOM Header] as b
            on a.[Production BOM No_] = b.[No_]
            where cast(b.[timestamp] as bigint) > ?;
        </sourceQuery>
        <sourceQueryParam>
            select rowvers from nav.fnc_last_rowvers_get('nav.tbl_int_prod_bom_header');
        </sourceQueryParam>
        <targetTable>nav.tbl_int_prod_bom_line_load</targetTable>
        <!-- NO CALLBACK HERE -->
        <targetCallback />
    </step>
    <step name="Production BOM Version" order="3">
        <targetCallfront>truncate table nav.tbl_int_prod_bom_vers_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[Production BOM No_],
                a.[Version Code],
                a.[Description],
                a.[Starting Date],
                a.[Unit of Measure Code],
                a.[Last Date Modified],
                a.[Status],
                a.[No_ Series],
                a.[Location Code],
                current_timestamp as mod_de
            from [dbo].[Live_any$Production BOM Version] as a
            inner join [dbo].[Live_any$Production BOM Header] as b
            on a.[Production BOM No_] = b.[No_]
            where cast(b.[timestamp] as bigint) > ?;
        </sourceQuery>
        <sourceQueryParam>
            select rowvers from nav.fnc_last_rowvers_get('nav.tbl_int_prod_bom_header');
        </sourceQueryParam>
        <targetTable>nav.tbl_int_prod_bom_vers_load</targetTable>
        <!-- CALLBACK FOR ALL BOM TABLES -->
        <targetCallback>call nav.prc_prod_bom_all_merge_load();</targetCallback>
    </step>
    <step name="Routing Header" order="4">
        <targetCallfront>truncate table nav.tbl_int_routing_header_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[No_],
                a.[Description],
                a.[Description 2],
                a.[Search Description],
                a.[Last Date Modified],
                a.[Status],
                a.[Type],
                a.[Version Nos_],
                a.[No_ Series],
                current_timestamp as mod_de
            from [dbo].[Live_any$Routing Header] as a
            where cast(a.[timestamp] as bigint) > ?;
        </sourceQuery>
        <sourceQueryParam>
            select rowvers from nav.fnc_last_rowvers_get('nav.tbl_int_routing_header');
        </sourceQueryParam>
        <targetTable>nav.tbl_int_routing_header_load</targetTable>
        <!-- NO CALLBACK HERE -->
        <targetCallback />
    </step>
    <step name="Routing Line" order="5">
        <targetCallfront>truncate table nav.tbl_int_routing_line_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[Routing No_],
                a.[Version Code],
                a.[Operation No_],
                a.[Next Operation No_],
                a.[Previous Operation No_],
                a.[Type],
                a.[No_],
                a.[Work Center No_],
                a.[Work Center Group Code],
                a.[Description],
                a.[Setup Time],
                a.[Run Time],
                a.[Wait Time],
                a.[Move Time],
                a.[Fixed Scrap Quantity],
                a.[Lot Size],
                a.[Scrap Factor _],
                a.[Setup Time Unit of Meas_ Code],
                a.[Run Time Unit of Meas_ Code],
                a.[Wait Time Unit of Meas_ Code],
                a.[Move Time Unit of Meas_ Code],
                a.[Minimum Process Time],
                a.[Maximum Process Time],
                a.[Concurrent Capacities],
                a.[Send-Ahead Quantity],
                a.[Routing Link Code],
                a.[Standard Task Code],
                a.[Unit Cost per],
                a.[Recalculate],
                a.[Sequence No_ (Forward)],
                a.[Sequence No_ (Backward)],
                a.[Fixed Scrap Qty_ (Accum_)],
                a.[Scrap Factor _ (Accumulated)],
                a.[Machine Efficiency (_)],
                a.[No_ Of Workers],
                a.[Net Setup Time],
                a.[Net Run Time],
                a.[Description 2],
                current_timestamp as mod_de
            from [dbo].[Live_any$Routing Line] as a
            inner join [dbo].[Live_any$Routing Header] as b
            on a.[Routing No_] = b.[No_]
            where cast(b.[timestamp] as bigint) > ?;
        </sourceQuery>
        <sourceQueryParam>
            select rowvers from nav.fnc_last_rowvers_get('nav.tbl_int_routing_header');
        </sourceQueryParam>
        <targetTable>nav.tbl_int_routing_line_load</targetTable>
        <!-- NO CALLBACK HERE -->
        <targetCallback />
    </step>
    <step name="Routing Version" order="6">
        <targetCallfront>truncate table nav.tbl_int_routing_vers_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[Routing No_],
                a.[Version Code],
                a.[Description],
                a.[Starting Date],
                a.[Status],
                a.[Type],
                a.[Last Date Modified],
                a.[No_ Series],
                a.[Location Code],
                current_timestamp as mod_de
            from [dbo].[Live_any$Routing Version] as a
            inner join [dbo].[Live_any$Routing Header] as b
            on a.[Routing No_] = b.[No_]
            where cast(b.[timestamp] as bigint) > ?;
        </sourceQuery>
        <sourceQueryParam>
            select rowvers from nav.fnc_last_rowvers_get('nav.tbl_int_routing_header');
        </sourceQueryParam>
        <targetTable>nav.tbl_int_routing_vers_load</targetTable>
        <!-- CALLBACK FOR ALL ROUTING TABLES -->
        <targetCallback>call nav.prc_routing_all_merge_load();</targetCallback>
    </step>
    <step name="Item" order="7">
        <targetCallfront>truncate table nav.tbl_int_item_load;</targetCallfront>
        <sourceQuery>
            select
                cast(a.[timestamp] as bigint) as [timestamp],
                a.[No_],
                a.[No_ 2],
                a.[Description],
                a.[Search Description],
                a.[Description 2],
                a.[Base Unit of Measure],
                a.[Price Unit Conversion],
                a.[Type],
                a.[Inventory Posting Group],
                a.[Shelf No_],
                a.[Item Disc_ Group],
                a.[Allow Invoice Disc_],
                a.[Statistics Group],
                a.[Commission Group],
                a.[Unit Price],
                a.[Price_Profit Calculation],
                a.[Profit _],
                a.[Costing Method],
                a.[Unit Cost],
                a.[Standard Cost],
                a.[Last Direct Cost],
                a.[Indirect Cost _],
                a.[Cost is Adjusted],
                a.[Allow Online Adjustment],
                a.[Vendor No_],
                a.[Vendor Item No_],
                a.[Lead Time Calculation],
                a.[Reorder Point],
                a.[Maximum Inventory],
                a.[Reorder Quantity],
                a.[Alternative Item No_],
